#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tareaRecuperacion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RECUPERACION")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertABONOS(ABONOS instance);
    partial void UpdateABONOS(ABONOS instance);
    partial void DeleteABONOS(ABONOS instance);
    partial void InsertCLIENTES(CLIENTES instance);
    partial void UpdateCLIENTES(CLIENTES instance);
    partial void DeleteCLIENTES(CLIENTES instance);
    partial void InsertCREDITOS(CREDITOS instance);
    partial void UpdateCREDITOS(CREDITOS instance);
    partial void DeleteCREDITOS(CREDITOS instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ABONOS> ABONOS
		{
			get
			{
				return this.GetTable<ABONOS>();
			}
		}
		
		public System.Data.Linq.Table<CLIENTES> CLIENTES
		{
			get
			{
				return this.GetTable<CLIENTES>();
			}
		}
		
		public System.Data.Linq.Table<CREDITOS> CREDITOS
		{
			get
			{
				return this.GetTable<CREDITOS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ABONOS")]
	public partial class ABONOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_MONTO;
		
		private System.Nullable<int> _CODIGO_CREDITO;
		
		private System.Nullable<decimal> _ABONO;
		
		private string _FECHA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_MONTOChanging(int value);
    partial void OnCODIGO_MONTOChanged();
    partial void OnCODIGO_CREDITOChanging(System.Nullable<int> value);
    partial void OnCODIGO_CREDITOChanged();
    partial void OnABONOChanging(System.Nullable<decimal> value);
    partial void OnABONOChanged();
    partial void OnFECHAChanging(string value);
    partial void OnFECHAChanged();
    #endregion
		
		public ABONOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_MONTO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGO_MONTO
		{
			get
			{
				return this._CODIGO_MONTO;
			}
			set
			{
				if ((this._CODIGO_MONTO != value))
				{
					this.OnCODIGO_MONTOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_MONTO = value;
					this.SendPropertyChanged("CODIGO_MONTO");
					this.OnCODIGO_MONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_CREDITO", DbType="Int")]
		public System.Nullable<int> CODIGO_CREDITO
		{
			get
			{
				return this._CODIGO_CREDITO;
			}
			set
			{
				if ((this._CODIGO_CREDITO != value))
				{
					this.OnCODIGO_CREDITOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_CREDITO = value;
					this.SendPropertyChanged("CODIGO_CREDITO");
					this.OnCODIGO_CREDITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABONO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ABONO
		{
			get
			{
				return this._ABONO;
			}
			set
			{
				if ((this._ABONO != value))
				{
					this.OnABONOChanging(value);
					this.SendPropertyChanging();
					this._ABONO = value;
					this.SendPropertyChanged("ABONO");
					this.OnABONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="VarChar(100)")]
		public string FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTES")]
	public partial class CLIENTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_CLIENTE;
		
		private string _NOMBRE1;
		
		private string _NOMBRE2;
		
		private string _APELLIDO1;
		
		private string _APELLIDO2;
		
		private string _DPI;
		
		private string _NIT;
		
		private string _DIRECCION;
		
		private string _TELEFONO;
		
		private string _SALARIO;
		
		private string _ESTADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_CLIENTEChanging(int value);
    partial void OnCODIGO_CLIENTEChanged();
    partial void OnNOMBRE1Changing(string value);
    partial void OnNOMBRE1Changed();
    partial void OnNOMBRE2Changing(string value);
    partial void OnNOMBRE2Changed();
    partial void OnAPELLIDO1Changing(string value);
    partial void OnAPELLIDO1Changed();
    partial void OnAPELLIDO2Changing(string value);
    partial void OnAPELLIDO2Changed();
    partial void OnDPIChanging(string value);
    partial void OnDPIChanged();
    partial void OnNITChanging(string value);
    partial void OnNITChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnSALARIOChanging(string value);
    partial void OnSALARIOChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public CLIENTES()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_CLIENTE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGO_CLIENTE
		{
			get
			{
				return this._CODIGO_CLIENTE;
			}
			set
			{
				if ((this._CODIGO_CLIENTE != value))
				{
					this.OnCODIGO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_CLIENTE = value;
					this.SendPropertyChanged("CODIGO_CLIENTE");
					this.OnCODIGO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE1", DbType="VarChar(100)")]
		public string NOMBRE1
		{
			get
			{
				return this._NOMBRE1;
			}
			set
			{
				if ((this._NOMBRE1 != value))
				{
					this.OnNOMBRE1Changing(value);
					this.SendPropertyChanging();
					this._NOMBRE1 = value;
					this.SendPropertyChanged("NOMBRE1");
					this.OnNOMBRE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE2", DbType="VarChar(100)")]
		public string NOMBRE2
		{
			get
			{
				return this._NOMBRE2;
			}
			set
			{
				if ((this._NOMBRE2 != value))
				{
					this.OnNOMBRE2Changing(value);
					this.SendPropertyChanging();
					this._NOMBRE2 = value;
					this.SendPropertyChanged("NOMBRE2");
					this.OnNOMBRE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO1", DbType="VarChar(100)")]
		public string APELLIDO1
		{
			get
			{
				return this._APELLIDO1;
			}
			set
			{
				if ((this._APELLIDO1 != value))
				{
					this.OnAPELLIDO1Changing(value);
					this.SendPropertyChanging();
					this._APELLIDO1 = value;
					this.SendPropertyChanged("APELLIDO1");
					this.OnAPELLIDO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO2", DbType="VarChar(100)")]
		public string APELLIDO2
		{
			get
			{
				return this._APELLIDO2;
			}
			set
			{
				if ((this._APELLIDO2 != value))
				{
					this.OnAPELLIDO2Changing(value);
					this.SendPropertyChanging();
					this._APELLIDO2 = value;
					this.SendPropertyChanged("APELLIDO2");
					this.OnAPELLIDO2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPI", DbType="VarChar(15)")]
		public string DPI
		{
			get
			{
				return this._DPI;
			}
			set
			{
				if ((this._DPI != value))
				{
					this.OnDPIChanging(value);
					this.SendPropertyChanging();
					this._DPI = value;
					this.SendPropertyChanged("DPI");
					this.OnDPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="VarChar(15)")]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this.OnNITChanging(value);
					this.SendPropertyChanging();
					this._NIT = value;
					this.SendPropertyChanged("NIT");
					this.OnNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(100)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(10)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALARIO", DbType="VarChar(100)")]
		public string SALARIO
		{
			get
			{
				return this._SALARIO;
			}
			set
			{
				if ((this._SALARIO != value))
				{
					this.OnSALARIOChanging(value);
					this.SendPropertyChanging();
					this._SALARIO = value;
					this.SendPropertyChanged("SALARIO");
					this.OnSALARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(100)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CREDITOS")]
	public partial class CREDITOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_CREDITO;
		
		private System.Nullable<int> _CODIGO_CLIENTE;
		
		private System.Nullable<decimal> _MONTO;
		
		private string _ESTADO;
		
		private string _FECHA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_CREDITOChanging(int value);
    partial void OnCODIGO_CREDITOChanged();
    partial void OnCODIGO_CLIENTEChanging(System.Nullable<int> value);
    partial void OnCODIGO_CLIENTEChanged();
    partial void OnMONTOChanging(System.Nullable<decimal> value);
    partial void OnMONTOChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnFECHAChanging(string value);
    partial void OnFECHAChanged();
    #endregion
		
		public CREDITOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_CREDITO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGO_CREDITO
		{
			get
			{
				return this._CODIGO_CREDITO;
			}
			set
			{
				if ((this._CODIGO_CREDITO != value))
				{
					this.OnCODIGO_CREDITOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_CREDITO = value;
					this.SendPropertyChanged("CODIGO_CREDITO");
					this.OnCODIGO_CREDITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_CLIENTE", DbType="Int")]
		public System.Nullable<int> CODIGO_CLIENTE
		{
			get
			{
				return this._CODIGO_CLIENTE;
			}
			set
			{
				if ((this._CODIGO_CLIENTE != value))
				{
					this.OnCODIGO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_CLIENTE = value;
					this.SendPropertyChanged("CODIGO_CLIENTE");
					this.OnCODIGO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this.OnMONTOChanging(value);
					this.SendPropertyChanging();
					this._MONTO = value;
					this.SendPropertyChanged("MONTO");
					this.OnMONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(100)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="VarChar(100)")]
		public string FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
